### ISSUE TITLE
DateTimeOffset to Zulu Time String (needs special handling)

### ISSUE THREAD

**Issue by alikalfaoglu** [rpgmaker/NetJSON#104]
When we serialize a datetimeoffset value, netjson serializes object with all public properties instead of serializing into Zulu DateTime format. For ex;
Datetimeoffset with a value of "**2016-02-22T13:51:51.3082087+02:00**" in zulu format is serialized as   **"DateTime":"2016-02-22T13:51:51.3082087","UtcDateTime":"2016-02-22T11:51:51.3082087","LocalDateTime":"2016-02-22T13:51:51.3082087","Date":"2016-02-22T00:00:00.0","Day":22,"DayOfWeek":Monday,"DayOfYear":53,"Hour":13,"Millisecond":308,"Minute":51,"Month":2,"Offset":"02:00:00","Second":51,"Ticks":635917459113082087,"UtcTicks":635917387113082087,"TimeOfDay":"13:51:51.3082087","Year":2016**
As far as i can see, DateTimeOffset is not handled specially. And this causes an increase in length from  33 bytes to 386 bytes.
I don't know if this is left as is on purpose (maybe handling specially cause some performance problems), but we'll gain a lot it works directly on zulu format.

**Comment by rpgmaker** [comment]
Have you tried using the timezone options?

NetJSON.TimeZoneFormat = Unspecified | Utc | Local (default: Unspecified)
            - This allows you to include the timezone information as part of serialization

Does it helps in anyway or is it that the output values does not match what you are looking for?

Try using the Utc option if that will give you the expected value.

Thanks,

**Comment by alikalfaoglu** [comment]
Yes i did but upon your request,I tried once more with DateFormat = JsonNetISO and TimeZoneFormat = Utc. Resulting output is similar to previous one;

 **"DateTime":"2016-02-24T09:41:57.8170284Z","UtcDateTime":"2016-02-24T07:41:57.8170284Z","LocalDateTime":"2016-02-24T09:41:57.8170284Z","Date":"2016-02-24T00:00:00.0Z","Day":24,"DayOfWeek":Wednesday,"DayOfYear":55,"Hour":9,"Millisecond":817,"Minute":41,"Month":2,"Offset":"02:00:00","Second":57,"Ticks":635919037178170284,"UtcTicks":635918965178170284,"TimeOfDay":"09:41:57.8170284","Year":2016}** 

instead of just this 

**"2016-02-24T09:41:57.8170284+02:00"**

The problem is DateTimeOffset struct serialized with public properties like all other objects but it actually needs special treatment to achieve the resulting string above. No need to serialize UtcDateTime / LocalDateTime / Date / Day etc. public properties additionally. Otherwise this adds an 353 bytes additional length per DateTimeOffset public property.

Our products are used simultaneously in different time zones therefore we had to use DateTimeOffset struct instead of DateTime in all of our objects. This is a huge cost for us.

As far as I can see right now, this is the only problem left that stops us using NetJSON as our primary JSON serializer in our projects.

Thanks.

**Comment by rpgmaker** [comment]
I understand now. I will make the changes tonight to include the proper serialization for datetime offset. I will just extract the datetime portion of it for serialization and deserialization. So just to explain, you will need to select timezone.local after my changes to get the exact output you are looking for. 


Thanks,

**Comment by rpgmaker** [comment]
Please test. I believe this should fix the issue. An example of how to test it is below using the new settings class

            var settings = new NetJSONSettings { TimeZoneFormat = NetJSONTimeZoneFormat.Local, DateFormat = NetJSONDateFormat.ISO };
            var dateTimeOffset = DateTimeOffset.FromFileTime(DateTime.Now.ToFileTime());
            var json = NetJSON.Serialize(dateTimeOffset, settings);

            var dateTimeOffset2 = NetJSON.Deserialize<DateTimeOffset>(json, settings);

            Assert.AreEqual(dateTimeOffset, dateTimeOffset2);

**Comment by alikalfaoglu** [comment]
Just tested. 
- Additional fields are not serialized which is fine. 
- When DateTimeOffset offset value is same with OS timezone, no problem with serialized/deserialized value. (In my case, it is +2.00 Istanbul ) 
- When DateTimeOffset value is different from OS timezone, serialized / deserialized values are not equal.
* `Serialized with Newtonsoft : **2016-02-25T10:21:33+04:00**` (The exact value I gave is this - I created datetimeoffset value manually with timezone (+04) different from OS timezone (+02))
* `Serialized with NetJSON : 2016-02-25T10:21:33.0+0200` (OS timezone is serialized i guess )

Thanks.

**Comment by rpgmaker** [comment]
I will fix that. It happens to be os because I did not extract the offset for the datetime offset object and only took the datetime object.

**Comment by rpgmaker** [comment]
Can you try it again and let me know if it is fixed now?

Thanks,

**Comment by alikalfaoglu** [comment]
Still having the same issue.
if you can change your test code with this you'll reproduce the problem..
```
[TestMethod]
        public void SerializeDateTimeOffSet() {
            var settings = new NetJSONSettings { TimeZoneFormat = NetJSONTimeZoneFormat.Local, DateFormat = NetJSONDateFormat.ISO };
            //var dateTimeOffset = new DateTimeOffset(DateTime.Now);
            var now = DateTime.Now;
            var dateTimeOffset = new DateTimeOffset(now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second, new TimeSpan(4, 0, 0));
            var json = NetJSON.Serialize(dateTimeOffset, settings);

            var dateTimeOffset2 = NetJSON.Deserialize<DateTimeOffset>(json, settings);

            Assert.AreEqual(dateTimeOffset, dateTimeOffset2);
        }
```
Thanks.

**Comment by rpgmaker** [comment]
That is interesting. I will try it. I tested using a datetimeoffset that is different from my local and it works fine. If you look at my unit test I used one for Tokyo datetime  offset. But I will give it one more try and get back to you. 

Thanks

**Comment by rpgmaker** [comment]
It is definitely fixed now :). In my previous test, I did not check that i was not testing datetimeoffset. The main issue was that I was convert the json iso format string to datetime and applying the offset to datetime itself rather than preserving it and adding it to offset object itself.

Please verify and get back to me.

Thanks,

**Comment by alikalfaoglu** [comment]
YES, it is definitely fixed now. Now I'll check for memory leaks.

Thanks..
